---
# tasks file for license role
- name: Ensure EULA Accepted
  assert:
    that:
      - tower_license.eula_accepted
    fail_msg: "You must accept the EULA by passing in the param eula_accepted as true"

- name: Install the tower license
  awx.awx.tower_license:
    data:                           "{{ tower_license.data }}"
    eula_accepted:                  "{{ tower_license.eula_accepted }}"
    tower_username:                 "{{ tower_username | default(omit) }}"
    tower_password:                 "{{ tower_password | default(omit) }}"
    tower_oauthtoken:               "{{ tower_oauthtoken | default(omit) }}"
    tower_host:                     "{{ tower_hostname }}"
    tower_config_file:              "{{ tower_config_file | default(omit) }}"
    validate_certs:                 "{{ tower_validate_certs | default('true') }}"
  no_log: "{{ tower_configuration_license_secure_logging }}"
  when: tower_license is defined
