---
- name: Output Vault Values
  hosts: clients
  gather_facts: False
  tasks:
    - name: Get KV Data
      uri:
        url: "{{ lookup('env', 'VAULT_ADDR') }}/v1/kv/data/{{ inventory_hostname }}"
        method: GET
        headers:
          Content-Type: application/json
          X-Vault-Token: "{{ lookup('env','VAULT_TOKEN') }}"
        return_content: yes
        status_code: 200
      register: auth
      delegate_to: localhost
    -  debug:
        msg: "The current password for {{ inventory_hostname }} is: {{ auth.json.data.data.password }}"