---
  # Need to install custom modules
  # pip install ansible-modules-hashivault

- name: Demo Playbook
  hosts: web
  become: yes
  gather_facts: no
  tasks:
    - name: Get Secret from Vault for SSH OTP
      hashivault_write:
        secret: "/ssh-client-signer/sign/centos6"
        data:
          public_key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
      register: vault_creds
      delegate_to: localhost
      run_once: yes
      become: no
    - name: write out the signed file
      copy:
        content: "{{ vault_creds.data.data.signed_key }}"
        dest: "~/.ssh/id_rsa-cert.pub"
      delegate_to: localhost
      run_once: yes
      become: no
    - set_fact:
        ansible_user: "centos"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_port: 2222

    - name: Wait for the connection to be online
      wait_for_connection:
        delay: 30
        sleep: 5
        timout: 300

    - name: Install http
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - php
      - git
    - name: http service state
      service: name=httpd state=started enabled=yes
