Vagrant.configure("2") do |config|
  config.vm.define "goodbox" do |goodbox|
    goodbox.vm.box = "debian/jessie64"
    goodbox.vm.network "private_network", ip: "192.168.33.10"
    goodbox.vm.provision :ansible do |ansible|
      ansible.playbook = "provisionning/good-playbook.yaml"
      ansible.verbose = "-v"
    end
  end
  config.vm.define "badbox" do |badbox|
    badbox.vm.box = "debian/jessie64"
    badbox.vm.network "private_network", ip: "192.168.33.11"
    badbox.vm.provision :ansible do |ansible|
      ansible.playbook = "provisionning/bad-playbook.yaml"
      ansible.verbose = "-v"
    end
  end  
end