name: Matrix-Build

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11x, 1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/alyarctiq/actions-go-acme

    - name: Run end-to-end tests on macOS
      if: github.event_name == 'pull_request' && matrix.platform == 'macos-latest'
      run: go build -v ./...
      env:
        GOPATH: /Users/runner/runners/2.161.0/work/actions-go-acme/go

            
    - name: Run end-to-end tests on Linux
      if: github.event_name == 'pull_request' && matrix.platform == 'ubuntu-latest'
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/actions-go-acme/go 

    - name: Run end-to-end tests on Windows
      if: github.event_name == 'pull_request' && matrix.platform == 'windows-latest'
      run: go build -v .
      env:
       GOPATH: d:\a\actions-go-acme\go\
