name: Run-On-PR
on: [pull_request]
jobs:

  build:
    name: Build-Run-On-PR
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Debug PATH - PRE
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

    #- name: Check out code into the Go module directory
    #  uses: actions/checkout@v1
    
    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/alyarctiq/actions-go-acme


    - name: Debug PWD
      run: |
        pwd
        ls -l

    - name: Debug POST
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      env:
        GOPATH: /home/runner/work/actions-go-acme/go  
  
    - name: Build/Test
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/actions-go-acme/go  

    - name: Notify Slack Of Failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"aly-test\",\"text\":\":github: :package: Package PR-Build-Test Failed !! Fix Your Code! :booom:\",\"username\":\"GitHub Action\"}'

    - name: Notify Slack Success 
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"aly-test\",\"text\":\":github: :package: Package PR-Build-Test Success !! :celebrate:\",\"username\":\"GitHub Action\"}' 
