---
tower_hostname: ""
tower_username: ""
tower_password: ""  # Put in a vault at vars/tower-secrets.yml when tower_secrets: true
tower_oauthtoken: ""
validate_certs: false
tower_configuration_users_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
