---
- name: Create Virtual Network Inteface Card
  delegate_to: localhost
  azure_rm_networkinterface:
    resource_group: "{{ lab_name }}-{{ rg_name }}"
    name: "{{ inventory_hostname }}-nic"
    virtual_network: "{{ lab_name }}-{{ vnet_name }}"
    subnet_name: "{{ lab_name }}-{{ vnet_subnet_name }}"
    security_group: "{{ sec_group_name }}-{{ rg_name }}"
    public_ip_name: "{{ inventory_hostname }}-{{ public_ip_name }}"
    tags: "{{ tag }}"
    #ip_configurations: 
    #  - name: ipconfig1
    #    public_ip_address_name: "{{ inventory_hostname }}-{{ public_ip_name }}"

- name: Create VM
  delegate_to: localhost
  azure_rm_virtualmachine:
    resource_group: "{{ lab_name }}-{{ rg_name }}"
    name: "{{ inventory_hostname }}"
    vm_size: "{{ vm_size }}"
    tags: "{{ tag }}"
    admin_username: azureuser
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/azureuser/.ssh/authorized_keys"
        key_data: "{{ key_data }}"
    network_interfaces: "{{ inventory_hostname }}-nic"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
    managed_disk_type: Standard_LRS