apiVersion: operations.arctiq.ca/v1alpha1
kind: AppTeam
metadata:
  name: appteamxyz
spec:
  admin_groups:
    - "admin_xyz@arctiq.ca"
    - "admin2_xyz@arctiq.ca"
  edit_groups:
    - "edit_xyz@arctiq.ca"
  view_groups:
    - "view_xyz@arctiq.ca"
