apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.name }}
  annotations:
    "consul.hashicorp.com/service-tags": "cheers,tgif"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer

