---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: ingress
spec:
  secretName: wildcard-cert
  dnsNames:
  - '*.arctiqtim.team.arctiq.ca'
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
