apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
spec:
  containers:
    - name: nginx-privileged
      image: nginx:latest
 #     securityContext:
 #       privileged: true
 #       runAsUser: 0
