- name: Gather Facts
  hosts: london_cisco_nxos
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Get Cisco NXOS Facts
      nxos_facts:
        gather_subset: all
        gather_network_resources: 
          - 'l3_interfaces'
          - 'l2_interfaces'
          
    - name: Verify L2 is Config on Device Matches Code
      nxos_l2_interfaces:
        config: "{{ ansible_network_resources['l2_interfaces'] }}"
      register: nxos_l2

    - name: Verify L3 is Config on Device Matches Code
      nxos_l3_interfaces:
        config: "{{ ansible_network_resources['l3_interfaces'] }}"
      register: nxos_l3

    - name: Ensure Config Matches Code
      assert:
        that: 
          - not nxos_l2.changed
          - not nxos_l3.changed

    - name: Merge NXOS VLAN Configuration
      nxos_vlans:
        config: "{{ london_cisco_nxos_l2_vlans }}"
        state: merged
    
    - name: Layer 2 Switchport Configuration
      nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: layer2
            enabled: true
      loop: "{{ london_cisco_nxos_l2_config }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Label Switchports
      nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
      loop: "{{ london_cisco_nxos_l2_name }}"

    - name: Layer 2 Port Configuration
      nxos_l2_interfaces:
          config: "{{ london_cisco_nxos_l2_config }}"
          state: merged

    - name: Layer 3 Port Configuration
      nxos_l3_interfaces:
          config: "{{ london_cisco_nxos_l3_config }}"
          state: merged
    
    - name: Commit/Save Configuration
      cli_command:
        command: "{{ save_config }}"