---
- name: "Ensure virtual environment path exists"
  file:
    mode: "0755"
    owner: "awx"
    group: "awx"
    path: "{{ tower_venv_path }}"
    state: directory
  become: true

- name: "Ensure virtual environment has Ansible Tower base dependencies"
  pip:
    name: "{{ tower_venv_base_deps }}"
    umask: "{{ tower_venv_umask }}"
    virtualenv: "{{ tower_venv_path }}"
    virtualenv_command: "virtualenv"
    state: present
  become: true
