---
tower_settings:
  settings:
    AUTH_LDAP_BIND_PASSWORD: "{{ lookup('env', 'TOWER_PASS') }}"
    AUTH_LDAP_BIND_DN: "CN=tower ldap_bind,CN=Users,DC=cloud,DC=lab"
    AWX_TASK_ENV: {'GIT_SSL_NO_VERIFY': 'True'}
    AUTH_LDAP_SERVER_URI: "ldap://dc1.cloud.lab"
    # AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,ou=Users,dc=example,dc=com"
    AUTH_LDAP_GROUP_SEARCH:
      - DC=cloud,DC=lab
      - SCOPE_SUBTREE
      - "(objectClass=group)"
    AUTH_LDAP_GROUP_TYPE: "ActiveDirectoryGroupType"
    AUTH_LDAP_USER_SEARCH:
      - DC=cloud,DC=lab
      - SCOPE_SUBTREE
      - "(sAMAccountName=%(user)s)"
    AUTH_LDAP_START_TLS: False
    AUTH_LDAP_GROUP_TYPE_PARAMS: {}
    AUTH_LDAP_REQUIRE_GROUP: "CN=tower_users,CN=Users,DC=cloud,DC=lab"
    # Next name helps fetch Email addr and name from LDAP and save it in tower user.
    AUTH_LDAP_USER_ATTR_MAP:
      first_name: givenName
      last_name: sn
      email: mail
    # Global Network Admins becomes superuser in tower as soon as they login - only supports SU and System Auditor
    AUTH_LDAP_USER_FLAGS_BY_GROUP:
      is_superuser:
        - "CN=global_admins,OU=Global,DC=cloud,DC=lab"
    # This maps global admins to to global-network-admins org
    AUTH_LDAP_ORGANIZATION_MAP:
      global-network-admins:
        users: false
        remove_admins: true
        admins: "CN=global_admins,OU=Global,DC=cloud,DC=lab"
    # This maps all users to satellite-qe team and we need to add this team to all resources we create for them
    # that way users can access the things that their team has permissions for
    AUTH_LDAP_TEAM_MAP:
      global-network-admins:
        organization: global-network-admins
        users: "CN=global_admins,OU=Global,DC=cloud,DC=lab"
        remove: true
      global-helpdesk:
        organization: global-helpdesk
        users: "CN=global_helpdesk,OU=Global,DC=cloud,DC=lab"
        remove: true