apiVersion: v1
kind: ClusterRole
metadata:
  name: nginx-ingress 
rules:
  - resources:
    - services
    - endpoints
    verbs:
    - list
    - watch
  - resources:
    - configmaps
    - secrets
    verbs:
    - get
    - list
    - watch
  - resources:
    - pods 
    verbs:
    - list
  - resources:
    - events 
    verbs:
    - create 
    - patch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - list
    - watch
