apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.name }}
spec:
  ports:
    - name: vault
      port: 8200
    - name: vault-cluster
      port: 8201
  selector:
    app: {{ .Values.name }}
