---
- name: Add an inventory source
  awx.awx.tower_inventory_source:
    name:                                 "{{ source.name }}"  # REQUIRED
    new_name:                             "{{ source.new_name | default(omit) }}"
    description:                          "{{ source.description | default(omit) }}"
    inventory:                            "{{ source.inventory }}"  # REQUIRED
    source:                               "{{ source.source }}"  # REQUIRED
    source_path:                          "{{ source.source_path | default(omit) }}"
    source_script:                        "{{ source.source_script | default(omit) }}"
    source_vars:                          "{{ source.source_vars | default(omit) }}"
    credential:                           "{{ source.credential | default(omit) }}"
    source_regions:                       "{{ source.source_regions | default(omit) }}"
    instance_filters:                     "{{ source.instance_filters | default(omit) }}"
    group_by:                             "{{ source.group_by | default(omit) }}"
    overwrite:                            "{{ source.overwrite | default(omit) }}"
    overwrite_vars:                       "{{ source.overwrite_vars | default(omit) }}"
    custom_virtualenv:                    "{{ source.custom_virtualenv | default(omit) }}"
    timeout:                              "{{ source.timeout | default(omit) }}"
    verbosity:                            "{{ source.verbosity | default(omit) }}"
    update_on_launch:                     "{{ source.update_on_launch | default(omit) }}"
    update_cache_timeout:                 "{{ source.update_cache_timeout | default(omit) }}"
    source_project:                       "{{ source.source_project | default(omit) }}"
    update_on_project_update:             "{{ source.update_on_project_update | default(omit) }}"
    state:                                "{{ source.state | default(tower_state | default('present')) }}"
    notification_templates_started:       "{{ source.notification_templates_started | default(omit) }}"
    notification_templates_success:       "{{ source.notification_templates_success | default(omit) }}"
    notification_templates_error:         "{{ source.notification_templates_error | default(omit) }}"
    tower_config_file:                    "{{ tower_config_file | default(omit) }}"
    tower_host:                           "{{ tower_hostname | default(omit) }}"
    tower_username:                       "{{ tower_username | default(omit) }}"
    tower_password:                       "{{ tower_password | default(omit) }}"
    tower_oauthtoken:                     "{{ tower_oauthtoken | default(omit) }}"
    validate_certs:                       "{{ tower_validate_certs | default('false') }}"
  loop: "{{ tower_inventory_sources }}"
  loop_control:
    loop_var: source
  no_log: "{{ tower_configuration_inventory_sources_secure_logging }}"
  when: tower_inventory_sources is defined
...
