---
- name: Add tower host
  awx.awx.tower_host:
    name:             "{{ tower_hosts_item.name }}"
    new_name:         "{{ tower_hosts_item.new_name | default(omit) }}"
    description:      "{{ tower_hosts_item.description | default('') }}"
    inventory:        "{{ tower_hosts_item.inventory }}"
    enabled:          "{{ tower_hosts_item.enabled | default(True) }}"
    state:            "{{ tower_hosts_item.state | default(tower_state | default('present')) }}"
    variables:        "{{ tower_hosts_item.variables | default(omit) }}"
    tower_host:       "{{ tower_hostname }}"
    tower_username:   "{{ tower_username | default('admin') }}"
    tower_password:   "{{ tower_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default('false') }}"
  loop: "{{ tower_hosts }}"
  loop_control:
    loop_var: tower_hosts_item
  no_log: "{{ tower_configuration_hosts_secure_logging }}"
  when: tower_hosts is defined
