# permissions for end users to edit appteams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appteam-editor-role
rules:
- apiGroups:
  - operations.arctiq.ca
  resources:
  - appteams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operations.arctiq.ca
  resources:
  - appteams/status
  verbs:
  - get
