name: 'Issue parser and provision with Terraform'
on:
  issues:
    types: [opened]

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: 'Checkout' 
      uses: actions/checkout@v1
    - name: Parse latest GitHub issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: daniyalj/action-issue-parser@v8
      with:
        org_name: 'daniyalj'
        repo_name: 'actions-assistant-demo'
        global_email: 'daniyaljavedk@gmail.com'
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'init'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'plan'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: 'apply'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
