apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: weather
spec:
  secretName: weather-tls
  issuerRef:
    name: vault-issuer
  commonName: gke.weather.weirdscience.labs.arctiq.ca
  dnsNames:
  - www.gke.weather.weirdscience.labs.arctiq.ca
