kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "standard"
  labels:
    app: postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
